name: Selenium Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        browser: [chrome,firefox]
      fail-fast: false
    defaults:
      run:
        working-directory: BTTuan11/Selenium-framework

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cài Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1

      # - name: Chạy Selenium Tests
      #   run: mvn clean test -Dbrowser=chrome -Denv=dev -DsuiteXmlFile=testng-smoke.xml
      #   env:
      #     APP_PASSWORD: ${{ secrets.SAUCEDEMO_PASSWORD }}

      - name: Chạy test (${{ matrix.browser }})
        run: mvn clean test -Dbrowser=${{ matrix.browser }} -DsuiteXmlFile=testng-smoke.xml
        env:
          APP_PASSWORD: ${{ secrets.SAUCEDEMO_PASSWORD }}
      - name: Lưu kết quả test
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.browser }}
          path: |
            BTTuan11/Selenium-framework/target/surefire-reports/
            BTTuan11/Selenium-framework/target/**/*.png
          retention-days: 30